### ISSUE TITLE
Create a separate package containing Utils, meant to help writing unit tests only

### ISSUE THREAD

**Issue by monsieurleberre** [trakx/dotnet-utils#3]
Let's say we call it Trakx.Utils.Testing, it should contain the kind of stuff that we have in trakx-tool/src/Trakx.Tests.Helpers
It can then be referenced by our unit testing projects :)

**Comment by monsieurleberre** [comment]
@carlos-takeapps this may be a nice first issue to spend some time looking at the way we write tests, and get familiar with our way of doing things. @AymericNoel or myself will surely be able to help if you are unsure of what this is about.

**Comment by carlos-takeapps** [comment]
I am sorry, I just found this message. I will start with this tomorrow morning now that I have most of the environment set up.
